// packages/react/src/MdEditor.tsx
import {
  type CodeBlockToolsMode,
  createEditor,
  type EditorHandle,
  type FeatureName,
  type Locale,
} from '@altmanlib/milkdown-kit'
import {
  type CSSProperties,
  type Ref,
  useEffect,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
  useState,
} from 'react'

export interface MdEditorProps {
  /** Controlled Markdown content. */
  value?: string
  readonly?: boolean
  /** Creation-time only. */
  placeholder?: string
  /** Creation-time only. */
  uploadImage?: (file: File) => Promise<string>
  /** Creation-time only. */
  features?: Partial<Record<FeatureName, boolean>>
  /** Creation-time only. */
  locale?: Locale
  /** Creation-time only. Defaults to `always`. */
  codeBlockTools?: CodeBlockToolsMode
  /** Fired with the serialized Markdown, debounced by the editor (200ms). */
  onChange?: (markdown: string) => void
  /** Fired once after the editor is created. */
  onReady?: (editor: EditorHandle) => void
  className?: string
  style?: CSSProperties
  /** Imperative handle; `null` until the editor is ready. */
  ref?: Ref<EditorHandle | null>
}

export function MdEditor({
  value = '',
  readonly = false,
  placeholder,
  uploadImage,
  features,
  locale,
  codeBlockTools,
  onChange,
  onReady,
  className,
  style,
  ref,
}: MdEditorProps) {
  const rootRef = useRef<HTMLDivElement>(null)
  const [editor, setEditor] = useState<EditorHandle | null>(null)
  // The last value known to be in sync with the editor. External updates equal to it
  // are echoes of our own onChange and must not be written back (avoids cursor jumps).
  const syncedValueRef = useRef(value)
  const valueRef = useRef(value)
  const readonlyRef = useRef(readonly)
  const onChangeRef = useRef(onChange)
  const onReadyRef = useRef(onReady)

  useLayoutEffect(() => {
    valueRef.current = value
    readonlyRef.current = readonly
    onChangeRef.current = onChange
    onReadyRef.current = onReady
  })

  useImperativeHandle<EditorHandle | null, EditorHandle | null>(ref, () => editor, [editor])

  useEffect(() => {
    const root = rootRef.current
    if (!root) return

    let cancelled = false
    let instance: EditorHandle | null = null

    void (async () => {
      const created = await createEditor(root, {
        defaultValue: syncedValueRef.current,
        readonly: readonlyRef.current,
        placeholder,
        uploadImage,
        features,
        locale,
        codeBlockTools,
        onChange: (markdown) => {
          syncedValueRef.current = markdown
          onChangeRef.current?.(markdown)
        },
      })
      if (cancelled) {
        await created.destroy()
        return
      }
      instance = created
      if (valueRef.current !== syncedValueRef.current) {
        syncedValueRef.current = valueRef.current
        created.setMarkdown(valueRef.current)
      }
      created.setReadonly(readonlyRef.current)
      // Expose the handle in state first; onReady runs after the ref commit below.
      setEditor(created)
    })()

    return () => {
      cancelled = true
      setEditor(null)
      void instance?.destroy()
    }
    // Creation-time props only. value / readonly / onChange are handled separately.
  }, [])

  // Fire onReady only after useImperativeHandle has committed the current editor.
  useLayoutEffect(() => {
    if (!editor) return
    onReadyRef.current?.(editor)
  }, [editor])

  useEffect(() => {
    if (!editor || value === syncedValueRef.current) return
    syncedValueRef.current = value
    editor.setMarkdown(value)
  }, [editor, value])

  useEffect(() => {
    editor?.setReadonly(readonly)
  }, [editor, readonly])

  return (
    <div
      ref={rootRef}
      className={className ? `md-editor-host ${className}` : 'md-editor-host'}
      style={style}
    />
  )
}

// packages/vue/src/MdEditor.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, shallowRef, useTemplateRef, watch } from 'vue'

import {
  type CodeBlockToolsMode,
  createEditor,
  type EditorHandle,
  type FeatureName,
  type Locale,
} from '@altmanlib/milkdown-kit'

export interface MdEditorProps {
  /** Markdown content, used with `v-model`. */
  modelValue?: string
  readonly?: boolean
  /** Creation-time only. */
  placeholder?: string
  /** Creation-time only. */
  uploadImage?: (file: File) => Promise<string>
  /** Creation-time only. */
  features?: Partial<Record<FeatureName, boolean>>
  /** Creation-time only. */
  locale?: Locale
  /** Creation-time only. Defaults to `always`. */
  codeBlockTools?: CodeBlockToolsMode
}

const props = withDefaults(defineProps<MdEditorProps>(), {
  modelValue: '',
  readonly: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  'ready': [editor: EditorHandle]
}>()

const root = useTemplateRef<HTMLDivElement>('root')
const editor = shallowRef<EditorHandle | null>(null)

// The last value known to be in sync with the editor. External updates equal to it
// are echoes of our own emits and must not be written back (avoids cursor jumps).
let syncedValue = props.modelValue
let unmounted = false

onMounted(async () => {
  const instance = await createEditor(root.value!, {
    defaultValue: props.modelValue,
    readonly: props.readonly,
    placeholder: props.placeholder,
    uploadImage: props.uploadImage,
    features: props.features,
    locale: props.locale,
    codeBlockTools: props.codeBlockTools,
    onChange: (markdown) => {
      syncedValue = markdown
      emit('update:modelValue', markdown)
    },
  })
  if (unmounted) {
    await instance.destroy()
    return
  }
  editor.value = instance
  // Catch up with changes made while the editor was being created.
  if (props.modelValue !== syncedValue) {
    syncedValue = props.modelValue
    instance.setMarkdown(props.modelValue)
  }
  instance.setReadonly(props.readonly)
  emit('ready', instance)
})

watch(
  () => props.modelValue,
  (value) => {
    if (!editor.value || value === syncedValue) return
    syncedValue = value
    editor.value.setMarkdown(value)
  },
)

watch(
  () => props.readonly,
  (value) => editor.value?.setReadonly(value),
)

onBeforeUnmount(() => {
  unmounted = true
  void editor.value?.destroy()
  editor.value = null
})

defineExpose({ editor })
</script>

<template>
  <div ref="root" class="md-editor-host" />
</template>
